"""Drop dummy and add core tables

Revision ID: 2409e8132389
Revises: df2f9947c5ad
Create Date: 2026-04-03 10:40:41.825889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2409e8132389'
down_revision: Union[str, Sequence[str], None] = 'df2f9947c5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('is_sequenced', sa.Boolean(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionaries_id'), 'dictionaries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('daily_review_goal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('dictionary_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('reading', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('definition_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_term_reading', 'dictionary_terms', ['term', 'reading'], unique=False)
    op.create_index(op.f('ix_dictionary_terms_id'), 'dictionary_terms', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_terms_reading'), 'dictionary_terms', ['reading'], unique=False)
    op.create_index(op.f('ix_dictionary_terms_term'), 'dictionary_terms', ['term'], unique=False)
    op.create_table('media_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('progress_data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_progress_file_hash'), 'media_progress', ['file_hash'], unique=False)
    op.create_index(op.f('ix_media_progress_id'), 'media_progress', ['id'], unique=False)
    op.create_table('user_vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('reading', sa.String(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_term', 'user_vocab', ['user_id', 'term'], unique=False)
    op.create_index(op.f('ix_user_vocab_id'), 'user_vocab', ['id'], unique=False)
    op.drop_index(op.f('ix_dummy_test_id'), table_name='dummy_test')
    op.drop_table('dummy_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dummy_test_pkey'))
    )
    op.create_index(op.f('ix_dummy_test_id'), 'dummy_test', ['id'], unique=False)
    op.drop_index(op.f('ix_user_vocab_id'), table_name='user_vocab')
    op.drop_index('idx_user_term', table_name='user_vocab')
    op.drop_table('user_vocab')
    op.drop_index(op.f('ix_media_progress_id'), table_name='media_progress')
    op.drop_index(op.f('ix_media_progress_file_hash'), table_name='media_progress')
    op.drop_table('media_progress')
    op.drop_index(op.f('ix_dictionary_terms_term'), table_name='dictionary_terms')
    op.drop_index(op.f('ix_dictionary_terms_reading'), table_name='dictionary_terms')
    op.drop_index(op.f('ix_dictionary_terms_id'), table_name='dictionary_terms')
    op.drop_index('idx_term_reading', table_name='dictionary_terms')
    op.drop_table('dictionary_terms')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dictionaries_id'), table_name='dictionaries')
    op.drop_table('dictionaries')
    # ### end Alembic commands ###
